baseURL = "https://ronja-tutorials.com"
languageCode = "en-us"
title = "Ronja's tutorials"
theme = "ananke"
assetDir = "static"
disqusShortname = "disqus_vlgXjcPhg1"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "colorful"
    tabWidth = 2